export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const UPDATE_CURRENT_EMPLOYEE = 'UPDATE_CURRENT_EMPLOYEE';
export const DELETE_AN_EMPLOYEE = 'DELETE_AN_EMPLOYEE';