export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const UPDATE_CURRENT_EMPLOYEE = 'UPDATE_CURRENT_EMPLOYEE';
export const DELETE_AN_EMPLOYEE = 'DELETE_AN_EMPLOYEE';
export const UPDATE_SEARCH_EMPLOYEE_LIST = 'UPDATE_SEARCH_EMPLOYEE_LIST';
export const UPDATE_UNSELECTED_LIST = 'UPDATE_UNSELECTED_LIST';
export const UPDATE_FILTERED_VALUES = 'UPDATE_FILTERED_VALUES';
export const UPDATE_UNSELECTED_FILTER_LISTS = 'UPDATE_SELECTED_FILTER_LISTS';